name: CI - Purebas JS

on:
  push:
  branches: [main]

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkoun@v3
    - name: Instalar Node.js
    - uses: actions/setup-node@v3
    - with:
      node-version:
        -name: Ejecutar test
        run: node math.test.js
