name: CD - Deploy con Git Pull

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519_ivan_escobar
          chmod 600 ~/.ssh/id_ed25519_ivan_escobar
          ssh-keyscan 137.184.127.11 >> ~/.ssh/known_hosts

      - name: Conectarse al servidor y hacer git pull
        run: |
          ssh -i ~/.ssh/id_ed25519_ivan_escobar -o StrictHostKeyChecking=no alumno@137.184.127.11 "cd ~/lemp-sites/ivan_escobar && git pull origin main"
