name: CD - Deploy con Git Pull

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519_ivan_escobar
          chmod 600 ~/.ssh/id_ed25519_ivan_escobar
           ssh-keyscan -H 137.184.127.11 >> ~/.ssh/known_hosts

      - name: Hacer git pull en el servidor
        run: |
          ssh -i ~/.ssh/id_ed25519_ivan_escobar alumno@137.184.127.11 "cd ~/lemp-sites/ivan_escobar && git pull origin main"
