name: CD - Deploy con Git Pull

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Contraste al servidor y hacer git pull
        run: |
          ssh -o StrictHostKeyChecking=no alumno137.184.127.11 "
            cd ~/lemp-sites/ivan_escobar && git pull origin main "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
