name: CD - Deploy react con git pull

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: semaforo

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias y build
        run: |
          npm install
          npm run build

      - name: Run Deploy
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/lemp-sites/ivan_escobar/semaforo/
