name: CD - Deploy con Git Pull

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse al servidor y hacer git pull
        run: |
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519_ivan_escobar
          chmod 600 ~/.ssh/id_ed25519_ivan_escobar

          "
      - name: Test SSH connection
        run: ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no alumno@137.184.127.11 "echo Conectado correctamente"
